# Generated by Django 4.0.1 on 2022-01-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('courseNumber', models.IntegerField(max_length=5, unique=True)),
                ('instructorName', models.CharField(max_length=60)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
